#!/bin/bash

docker exec -it go-fyne-project /bin/bash -c 'CGO_ENABLED="1" GOOS="windows" CC="/usr/bin/x86_64-w64-mingw32-gcc" CXX="/usr/bin/x86_64-w64-mingw32-c++" go build -o /application/build/out.exe /application/main.go'